// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateOrder(ctx context.Context, customerID int64) (sql.Result, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error)
	FindProductByID(ctx context.Context, id int64) (Product, error)
	ListProducts(ctx context.Context) ([]Product, error)
	ReduceProductStock(ctx context.Context, arg ReduceProductStockParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
