// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders (
  customer_id
) VALUES (?)
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder, customerID)
}

const createOrderItem = `-- name: CreateOrderItem :execresult
INSERT INTO order_items (
  order_id,
  product_id,
  quantity,
  price_cents
) VALUES (?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID    int64 `json:"order_id"`
	ProductID  int64 `json:"product_id"`
	Quantity   int32 `json:"quantity"`
	PriceCents int32 `json:"price_cents"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceCents,
	)
}

const findProductByID = `-- name: FindProductByID :one
SELECT id, name, price_in_centers, quantity, created_at FROM products
WHERE id = ?
`

func (q *Queries) FindProductByID(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, findProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceInCenters,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, customer_id, created_at FROM orders
ORDER BY created_at
`

func (q *Queries) ListOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.ID, &i.CustomerID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, price_in_centers, quantity, created_at FROM products
ORDER BY name
`

func (q *Queries) ListProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceInCenters,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reduceProductStock = `-- name: ReduceProductStock :execresult
UPDATE products
SET quantity = quantity - ?
WHERE id = ? AND quantity >= ?
`

type ReduceProductStockParams struct {
	Quantity   int32 `json:"quantity"`
	ID         int64 `json:"id"`
	Quantity_2 int32 `json:"quantity_2"`
}

func (q *Queries) ReduceProductStock(ctx context.Context, arg ReduceProductStockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, reduceProductStock, arg.Quantity, arg.ID, arg.Quantity_2)
}
